language: ruby
script:
- bundle exec rspec spec
branches:
  only:
  - master
deploy:
  api_key:
    secure: Dao1aUC3qNfM1qBKlu90DpCwDoWeVnMQuGFm4jZJKpzcRtqV0jCkgGzB2efxm9W53QdgRhI4MAs4dbhT0xfMq3uYgzP+73yWewGEbtd1Q4dBEFy9nuDoW7e1lPOIvpnU85IPv0PdeGpRw5y7OV5W72xcmNsvrlcORomgNLLx7Ksvxrj69Gc6G6aLwSSE4dOjTWlT8dokBLI76RO+V4uPh/SNfEgaD3jXzKo2ey0esoIaU81NCR+/E1y6O3U+6ULQ9VrH6Ud2v408XQXHVppAJcZ4y9TR7dd54MZIb4e56rLHUq14QnVWc8ZzG5xRpck+G4hlK4bFasYW02ksriiiY/xamf5nA2/tBGBcij2Xfl9Llli9Qw1VuctJ5fh6R5lh53dkJFoRerTrrw8PWOXQNV5Zjes6xLYSqK2n1bDBBNfmVHGKJYDLfKVb4Pl5RSefPq5iKFNSNYCCBkiD6DsAaq7YkynXwfU+WOhaoho6PEzEoL4WYI91Y4fAnpBDr4LIuY5t79Y6lzUAEbXBtxK4f8xJzW1txAImVbCdisuTndSuSmLAzNwZ/i/UfeO3q+yjWG1dZxknYc8l4/Gq4E9/uU7fNe/EgDnNSUQFuG8Hnm+6j3gd+ix4xw27QtGCW1oiSBLohts0shrTne+4nYxUWRw7jZmj7YFov/kUNmjyvQ8=
