language: ruby
script:
- bundle exec rspec spec
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: d8T+H+pqdY5tg3ur1KaznG6KBnX6d95fKYLPt5EMSr6EnNXOkt3MJN+W7+w6mV3W916k0YxaNjNwCMB11pH/04GDXBZWDGbvIr3osryCd73oJOm8E9Zqkfnq3+uSaaQG9PrsJo7uLywWTAwcz5Q2kbAAdfFWufh8iaQ+ya6baEdnU1GZA/YXQI0caZhBn/M2LBIcPdrNbagSmgwFyI7geD3L0gXoAqQ+8LZ43ISDReq6Q5WrDsry/ZAGPdbOa90SYICNB4EyUfSzy0y2iWoaVurtgOXu0+fBLAzW8w2k/SYDnqRXV/EwGty0Ln37jxXk5LiQXRhgoGaQIbmKQl4v5DM2VgyOudmJyNkyBJ3TevjOsc5kgfhK9pZw5iP8qVHluFbIOK1W0MFq6iYRer38aMbaSJq/8xxKyGHrWStjABrD6Yvcc/MJecAu/qkXqfCRO4Ff7AmSXDQC++sTit/5y8rmENrOHVA1r8UlLfeX408I9aL3hQra30914EwSFiR/SrWkg+oklOA5eZjiQB5VxrLvv4MwdSHU5ZYsxf+OKrQNJ1zzNPsVw6SNT75WAzi+yqqP+gyRfBoTwktj7LfNg7WhSiCLtfteh4pnyEvNTCWyYDvL1xWHgDHt10PP0TAbO1Ro81Yfl4rp9P+kMmVdbOFacoxBLlv2LZV4zdPma9o=
  app: intense-savannah-56279
  on:
    repo: alanmulhall/shows
